[package]
name = "trees"
version = "0.1.0"
authors = [ "Boris Faure <billiob@gmail.com>" ]
license = "BSD-2-Clause"
edition = "2018"

[dependencies]
image = "*"
log = "*"
env_logger = "*"
pretty_env_logger = "0.2"
